-- SK60 RNAV flight plan. Generated by nav_system.lua.
-- Edit the waypoints table before a mission to pre-program/shared routes.
-- Columns: FRQ = VOR frequency (MHz), RAD = radial (degrees), DST = distance (NM).

local waypoints = {
    -- WPT   FRQ      RAD    DST
    [ 1] = { FRQ = 113.60, RAD = 278, DST =   8.5 },
    [ 2] = { FRQ = 113.60, RAD =  46, DST =   9.0 },
    [ 3] = { FRQ = 114.20, RAD = 105, DST =   9.0 },
    [ 4] = { FRQ = 117.35, RAD =  12, DST =  25.7 },
    [ 5] = { FRQ = 108.90, RAD = 355, DST =  12.0 },
    [ 6] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 7] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 8] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 9] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [10] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
}

return {
    waypoints = waypoints,
    state = {
        ["active_rnav_edit_segment"] = 3,
        ["active_waypoint"] = {
            ["index"] = 1,
            ["offset_distance_nm"] = 8.4999999999999982,
            ["offset_radial_deg"] = 278,
            ["vor_frequency_mhz"] = 113.60000000000001,
        },
        ["current_waypoint_index"] = 1,
        ["selected_heading_bug_deg"] = 262,
        ["selected_offset_distance_nm"] = 8.4999999999999982,
        ["selected_offset_radial_deg"] = 278,
        ["selected_vor_course_deg"] = 172,
        ["tuned_ndb_frequency_khz"] = 311,
        ["tuned_vor_frequency_mhz"] = 113.60000000000001,
        ["version"] = 1,
    },
}
